# print("bot_row_1_B_number:" + bot_row_1_B_number)
# print("bot_row_2_B_number:" + bot_row_2_B_number)
# print("bot_row_3_B_number:" + bot_row_3_B_number)
# print("bot_row_4_B_number:" + bot_row_4_B_number)
# print("bot_row_5_B_number:" + bot_row_5_B_number)
# ##I
# print("bot_row_1_I_number:" + bot_row_1_I_number)
# print("bot_row_2_I_number:" + bot_row_2_I_number)
# print("bot_row_3_I_number:" + bot_row_3_I_number)
# print("bot_row_4_I_number:" + bot_row_4_I_number)
# print("bot_row_5_I_number:" + bot_row_5_I_number)
# ##N
# print("bot_row_1_N_number:" + bot_row_1_N_number)
# print("bot_row_2_N_number:" + bot_row_2_N_number)
# print("bot_row_3_N_number:" + bot_row_3_N_number)
# print("bot_row_4_N_number:" + bot_row_4_N_number)
# print("bot_row_5_N_number:" + bot_row_5_N_number)
# ##G
# print("bot_row_1_G_number:" + bot_row_1_G_number)
# print("bot_row_2_G_number:" + bot_row_2_G_number)
# print("bot_row_3_G_number:" + bot_row_3_G_number)
# print("bot_row_4_G_number:" + bot_row_4_G_number)
# print("bot_row_5_G_number:" + bot_row_5_G_number)

# ##O
# print("bot_row_1_O_number:" + bot_row_1_O_number)
# print("bot_row_2_O_number:" + bot_row_2_O_number)
# print("bot_row_3_O_number:" + bot_row_3_O_number)
# print("bot_row_4_O_number:" + bot_row_4_O_number)
# print("bot_row_5_O_number:" + bot_row_5_O_number)
